# -*- fill-column: 120; -*-
#+TITLE: Publication
#+URI: /publication/
#+OPTIONS: toc:nil num:nil

[[[https://junzhouzhao.github.io/article/conference-list/][机器学习、数据挖掘以及人工智能等领域的主流国际会议]]]

- *[TPDS'23]* Runze Lei, Pinghui Wang, _Junzhou Zhao_, Lin Lan, Jing Tao, Chao Deng, Junlan Feng, Xidian Wang, and
  Xiaohong Guan. "Federated Learning over Coupled Graphs". IEEE Transactions on Parallel and Distributed Systems
  (TPDS), 2023. ~CCF-A~ ~联邦学习~ ~图计算~

- *[TKDE'23]* Yuanming Zhang, Pinghui Wang, Yiyan Qi, Kuankuan Cheng, _Junzhou Zhao_, Guangjian Tian, and Xiaohong Guan.
  "Fast Gumbel-Max Sketch and its Applications". IEEE Transactions on Knowledge and Data Engineering (TKDE), 2023.
  ~CCF-A~ ~大数据~ ~Sketch设计~

- *[AAAI'23]* Shuo Zhang, _Junzhou Zhao_, Pinghui Wang, Tianxiang Wang, Zi Liang, Jing Tao, Yi Huang, and Junlan Feng.
  "Multi-Action Dialog Policy Learning from Logged User Feedback". In /Proceedings of the 37th AAAI Conference on
  Artificial Intelligence (AAAI)/, 2023. ~CCF-A~ ~对话系统~

- *[SIGMOD'23]* Pinghui Wang, Chengjin Yang, Dongdong Xie, _Junzhou Zhao_, Hui Li, Jing Tao, and Xiaohong Guan. "An
  Effective and Differentially Private Protocol for Secure Distributed Cardinality Estimation". In /Proceedings of the
  ACM SIGMOD/PODS International Conference on Data Management (SIGMOD)/, 2023. ~CCF-A~ ~隐私计算~ ~安全多方计算~

- *[IJCAI'22]* Shuo Zhang, _Junzhou Zhao_, Pinghui Wang, Yu Li, Yi Huang, and Junlan Feng. "Think Before You Speak:
  Improving Multi-action Dialog Policy by Planning Single-Action Dialogs". In /Proceedings of the 31st International
  Joint Conference on Artificial Intelligence (IJCAI)/, 2022. [[[https://arxiv.org/abs/2204.11481][arXiv]]][[[file:assets/IJCAI22_MADP_slides.pdf][slides]]] ~CCF-A~ ~NLP~ ~对话系统~

- *[ICDE'22]* Juxiang Zeng, Pinghui Wang, Lin Lan, _Junzhou Zhao_, Feiyang Sun, Jing Tao, Junlan Feng, Min Hu, and
  Xiaohong Guan. "Accurate and Scalable Graph Neural Networks for Billion-Scale Graphs". /IEEE ICDE/ 2022. ~CCF-A~
  ~图神经网络~

- *[KDD'21]* Runze Lei, Pinghui Wang, Rundong Li, Peng Jia, _Junzhou Zhao_, Xiaohong Guan, and Chao Deng. "Fast Rotation
  Kernel Density Estimation over Data Streams". /ACM SIGKDD/ 2021. ~CCF-A~ ~数据流~ ~联邦学习~

- *[KDD'21]* _Junzhou Zhao_, Pinghui Wang, Chao Deng, and Jing Tao. "Temporal Biased Streaming Submodular Optimization".
  In /Proceedings of the 27th ACM SIGKDD Conference on Knowledge Discovery and Data Mining (ACM SIGKDD)/, 2021. [[[file:assets/KDD21_SSO_slides.pdf][slides]]]
  ~CCF-A~ ~数据流~ ~在线优化~ ~近似算法~

- *[TMC'21]* Feiyang Sun, Pinghui Wang, _Junzhou Zhao_, Nuo Xu, Juxiang Zeng, Jing Tao, Kaikai Song, Chao Deng, John
  C.S. Lui, and Xiaohong Guan. "Mobile Data Traffic Prediction by Exploiting Time-Evolving User Mobility Patterns".
  /IEEE Transactions on Mobile Computing/, 2021. ~CCF-A~ ~时空数据挖掘~

- *[TKDE'21]* Rundong Li, Pinghui Wang, Peng Jia, Xiangliang Zhang, _Junzhou Zhao_, Jing Tao, Ye Yuan, and Xiaohong
  Guan. "Approximately Counting Butterflies in Large Bipartite Graph Streams". /IEEE Transactions on Knowledge and Data
  Engineering (TKDE)/, 2021. ~CCF-A~ ~子图模式挖掘~

- *[SIGMOD'21]* Peng Jia, Pinghui Wang, _Junzhou Zhao_, Shuo Zhang, Yiyan Qi, Min Hu, Chao Deng, and Xiaohong Guan.
  "Bidirectionally Densifying LSH Sketches with Empty Bins". /ACM SIGMOD/ 2021. ~CCF-A~ ~LSH~ ~快速查询算法~

- *[SIGMOD'21]* Rundong Li, Pinghui Wang, Jiongli Zhu, _Junzhou Zhao_, Jia Di, Xiaofei Yang, and Kai Ye. "Building Fast
  and Compact Sketches for Approximately Multi-Set Multi-Membership Querying". /ACM SIGMOD/ 2021. ~CCF-A~ ~快速查询算法~

- *[TKDE'21]* Peng Jia, Pinghui Wang, _Junzhou Zhao_, Jing Tao, Ye Yuan, and Xiaohong Guan. "Erasable Virtual
  HyperLogLog for Approximating Cumulative Distribution over Data Streams". /IEEE Transactions on Knowledge and Data
  Engineering (TKDE)/, 2021. ~CCF-A~ ~数据流~ ~计数问题~

- *[ICDE'21]* Peng Jia, Pinghui Wang, _Junzhou Zhao_, Jing Tao, Ye Yuan, and Xiaohong Guan. "LogLog Filter: Filtering
  Cold Items within a Large Range over High Speed Data Streams". In /Proceedings of the 37th IEEE International
  Conference on Data Engineering (ICDE)/, 2021. ~CCF-A~ ~数据流~ ~在线算法~

- *[AAAI'21]* Shuo Zhang, _Junzhou Zhao_, Pinghui Wang, Nuo Xu, Yang Yang, Yiting Liu, Yi Huang, and Junlan Feng.
  "Learning to Check Contract Inconsistencies". In /Proceedings of the 35th AAAI Conference on Artificial Intelligence
  (AAAI)/, 2021. [[[https://arxiv.org/abs/2012.08150][arXiv]]][[[file:assets/AAAI2021-contract_poster.pdf][poster]]] ~CCF-A~ ~NLP~ ~合同文本~

- *[KAIS'21]* _Junzhou Zhao_, Pinghui Wang, Zhouguo Chen, Jianwei Ding, John C.S. Lui, Don Towsley, and Xiaohong Guan.
  "Tracking Triadic Cardinality Distributions for Burst Detection in High-Speed Graph Streams". /Knowledge and
  Information Systems (KAIS)/, 63:939-969, 2021. ~异常检测~ ~图数据流~ [[[https://arxiv.org/abs/1708.09089][arXiv]]]

- *[ACL'20]* Nuo Xu, Pinghui Wang, Long Chen, Li Pan, Xiaoyan Wang and _Junzhou Zhao_. "Distinguish Confusing Law
  Articles for Legal Judgment Prediction". In /Proceedings of the 58th Annual Meeting of the Association for
  Computational Linguistics (ACL)/, 2020. [[[https://arxiv.org/abs/2004.02557][arXiv]]] ~CCF-A~ ~NLP~ ~法律文书~

- *[WWW'20]* Yiyan Qi, Pinghui Wang, Yuanming Zhang, _Junzhou Zhao_, Guangjian Tian, and Xiaohong Guan. "Fast Generating
  A Large Number of Gumbel-Max Variables". /The Web Conference (WWW)/, 2020. [[[https://arxiv.org/abs/2002.00413][arXiv]]] ~CCF-A~ ~LSH~

- *[ICDE'20]* _Junzhou Zhao_, Pinghui Wang, Jing Tao, Shuo Zhang, and John C.S. Lui. "Continuously Tracking Core Items
  in Data Streams with Probabilistic Decays". In /Proceedings of the 36th IEEE International Conference on Data
  Engineering (IEEE ICDE)/, 2020. [[[file:assets/ICDE2020_full_version.pdf][full paper]]][[[file:assets/ICDE2020_slides.pdf][slides]]][[[file:assets/ICDE2020_poster.pdf][poster]]] ~CCF-A~ ~数据流~ ~在线优化~ ~近似算法~

- *[INS'20]* Lin Lan, Pinghui Wang, _Junzhou Zhao_, Jing Tao, John C.S. Lui, and Xiaohong Guan. "Improving Network
  Embedding with Partially Available Vertex and Edge Content". /Information Sciences/, 2020. ~图表示学习~

- *[TOIS'20]* Xiaoying Zhang, Hong Xie, _Junzhou Zhao_, and John C.S. Lui. "Understanding Assimilation-Contrast Effects
  in Online Rating Systems: Modeling, Debiasing and Applications". /ACM Transactions on Information Systems
  (TOIS)/, 2020. ~CCF-A~ ~推荐系统~

- *[IJCAI'19]* Nuo Xu, Pinghui Wang, Long Chen, Jing Tao, and Junzhou Zhao. "MR-GNN: Multi-Resolution and Dual Graph
  Neural Network for Predicting Structured Entity Interaction". In /Proceedings of the 28th International Joint
  Conference on Artificial Intelligence (IJCAI)/, 2019. [[[https://arxiv.org/abs/1905.09558][arXiv]]] ~CCF-A~ ~图表示学习~

- *[AAAI'19]* _Junzhou Zhao_, S. Shang, Pinghui Wang, John C.S. Lui, and Xiangliang Zhang. "Submodular Optimization over
  Streams with Inhomogeneous Decays". In /Proceedings of the 33rd AAAI Conference on Artificial Intelligence
  (AAAI)/, 2019. [[[https://arxiv.org/abs/1811.05652][arXiv]]] ~CCF-A~ ~数据流~ ~在线优化~ ~近似算法~

- *[ICDE'19]* _Junzhou Zhao_, S. Shang, Pinghui Wang, John C.S. Lui, and Xiangliang Zhang. "Tracking Influential Nodes
  in Time-Decaying Dynamic Interaction Networks". In /Proceedings of the 35th IEEE International Conference on Data
  Engineering (IEEE ICDE)/, 2019. [[[https://arxiv.org/abs/1810.07917][arXiv]]][[[file:assets/ICDE19_poster.pdf][poster]]] ~CCF-A~ ~社交网络~ ~影响力最大化~ ~近似算法~

- *[INS'19]* _Junzhou Zhao_, Pinghui Wang, and John C.S. Lui. "Optimizing Node Discovery on Networks: Problem
  Definitions, Fast Algorithms, and Observations". /Information Sciences (INS)/, 2019. [[[https://arxiv.org/abs/1703.04307][arXiv]]] ~优化算法~ ~近似算法~

- *[DMKD'19]* _Junzhou Zhao_, Pinghui Wang, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Sampling Online Social
  Networks by Random Walk with Indirect Jumps". /Data Mining and Knowledge Discovery (DMKD)/, 33:24-57, 2019. [[[https://arxiv.org/abs/1708.09081][arXiv]]]
  ~图采样~ ~近似算法~

- *[TKDE'18]* Pinghui Wang, _Junzhou Zhao_, Xiangliang Zhang, Zhenhua Li, Jiefeng Cheng, John C.S. Lui, Don Towsley,
  Jing Tao, and Xiaohong Guan. "MOSS-5: A Fast Method of Approximating Counts of 5-Node Graphlets in Large Graphs".
  /IEEE Transactions on Knowledge and Data Engineering (TKDE)/, 2018. [[[file:assets/TKDE18_poster.pdf][poster]]] ~CCF-A~ ~子图模式挖掘~

- *[KAIS'18]* Pinghui Wang, _Junzhou Zhao_, Xiangliang Zhang, Jing Tao, and Xiaohong Guan. "SNOD: A Fast Sampling Method
  of Exploring Node Orbit Degrees for Large Graphs". /Knowledge and Information Systems (KAIS)/, 2018.
  ~图采样~ ~网图数据~

- *[KAIS'18]* Pinghui Wang, _Junzhou Zhao_, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Fast Crawling Methods of
  Exploring Content Distributed Over Large Graphs". /Knowledge and Information Systems (KAIS)/, 2018. ~图采样~ ~近似算法~

- *[KAIS'18]* Pinghui Wang, _Junzhou Zhao_, Bruno Ribeiro, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Practical
  Characterization of Large Networks Using Neighborhood Information". /Knowledge and Information Systems (KAIS)/, 2018.
  ~图采样~ ~近似算法~

- *[TKDE'17]* Pinghui Wang, Yiyan Qi, John C.S. Lui, Don Towsley, _Junzhou Zhao_, Jing Tao. "Inferring Higher-Order
  Structure Statistics of Large Networks From Sampled Edges". /IEEE Transactions on Knowledge and Data Engineering
  (TKDE)/, 2017. ~CCF-A~ ~图采样~ ~近似算法~

- *[INS'17]* _Junzhou Zhao_, John C.S. Lui, Don Towsley, Pinghui Wang, and Xiaohong Guan. "I/O-Efficient Calculation of
  Group Closeness Centrality over Disk-Resident Graphs". /Information Sciences (INS)/, 2017. ~优化算法~ ~近似算法~ ~网图
  数据~

- *[RecSys'17]* Xiaoying Zhang, _Junzhou Zhao_, and John C.S. Lui. "Modeling the Assimilation-Contrast Effects in Online
  Product Rating Systems: Debiasing and Recommendations". In /Proceedings of the 11th ACM Conference on Recommendation
  Systems (RecSys)/, 2017. ~Awarded Best Paper~ ~推荐系统~

- *[ICDE'16]* Pinghui Wang, John C.S. Lui, Don Towsley, and Junzhou Zhao. "Minfer: A Method of Inferring Motif
  Statistics from Sampled Edges". In /Proceedings of the 32nd IEEE International Conference on Data Engineering
  (ICDE)/, 2016. ~CCF-A~ ~子图模式挖掘~ ~图采样~ ~近似算法~

- *[COSN'15]* _Junzhou Zhao_, John C.S. Lui, Don Towsley, Pinghui Wang, and Xiaohong Guan. "Tracking Triadic Cardinality
  Distributions for Burst Detection in Social Activity Streams". In /Proceedings of ACM Conference on Online Social
  Networks (COSN)/, 2015. [[[http://arxiv.org/abs/1411.3808][arXiv]]] ~异常检测~ ~图数据流~ ~近似算法~

- *[ICDE'15]* _Junzhou Zhao_, John C.S. Lui, Don Towsley, Pinghui Wang, and Xiaohong Guan. "A Tale of Three Graphs:
  Sampling Design on Hybrid Social-Affiliation Networks". In /Proceedings of the 31st IEEE International Conference on
  Data Engineering (ICDE)/, 2015. [[[file:assets/ICDE2015.pdf][pdf]]] ~CCF-A~ ~图采样~ ~近似算法~

- *[TIFS'14]* Pinghui Wang, Xiaohong Guang, _Junzhou Zhao_, Jing Tao, and Tao Qin. "A New Sketch Method for Measuring
  Host Connection Degree Distribution". /IEEE Transactions on Information Forensics and Security (TIFS)/, 2014. ~CCF-A~
  ~异常检测~ ~Sketch算法~

- *[SIMPLEX'14]* _Junzhou Zhao_, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Measuring and Maximizing Group
  Closeness Centrality over Disk-Resident Graphs". In /WWW SIMPLEX workshop/, 2014. [[[file:assets/SIMPLEX2014.pdf][pdf]]][[[file:assets/NodeGroup_TR.pdf][TR]]]
  ~Awarded Best Paper~ ~优化算法~ ~网图数据~

- *[COMNET'14]* _Junzhou Zhao_, John C.S. Lui, Don Towsley, and Xiaohong Guan. "WTF: Efficient Followee Selection for
  Cascading Outbreak Detection on Online Social Networks". /Computer Networks, Special Issue on Online Social
  Networks/, 2014. [[[file:assets/COMNET2014.pdf][pdf]]] ~异常检测~ ~网图数据~

- *[TKDD'14]* Pinghui Wang, _Junzhou Zhao_, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Unbiased Characterization of
  Node Pairs over Large Graphs". /ACM Transactions on Knowledge Discovery from Data (TKDD)/, 2014. [[[file:assets/TKDD2014_node_pair.pdf][pdf]]] ~图采样~ ~近似算法~

- *[Magazine'14]* Pinghui Wang, Wenbo He, and _Junzhou Zhao_. "A Tale of Three Social Networks: User Activity
  Comparations across Facebook, Twitter, and Foursquare". /IEEE Internet Computing/, 2014. [[[file:assets/IC2014.pdf][pdf]]] ~Featured Article~ ~社交网络~

- *[TKDD'14]* Pinghui Wang, John C.S. Lui, Bruno Ribeiro, Don Towsley, _Junzhou Zhao_, and Xiaohong Guan. "Efficiently
  Estimating Motif Statistics of Large Networks". /ACM Transactions on Knowledge Discovery from Data (TKDD)/, 2014.
  [[[http://arxiv.org/abs/1306.5288][arXiv]]] ~子图模式挖掘~ ~图采样算法~ ~近似算法~

- *[CrowdRec'13]* _Junzhou Zhao_, Xiaohong Guan, and Jing Tao. "On Analyzing Estimation Errors due to Constrained
  Connections in Online Review Systems". /RecSys CrowdRec workshop/, 2013. [[[http://arxiv.org/abs/1307.3687][arXiv]]] ~推荐系统~

- *[ICDE'13]* Pinghui Wang, _Junzhou Zhao_, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Sampling Node Pairs Over
  Large Graphs". In /Proceedings of the 29th IEEE International Conference on Data Engineering (ICDE)/, 2013. [[[file:assets/ICDE2013.pdf][pdf]]]
   ~CCF-A~ ~图采样~ ~近似算法~

- *[NetSciCom'11]* _Junzhou Zhao_, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Empirical Analysis of the Evolution
  of Follower Network: A Case Study on Douban". /IEEE INFOCOM NetSciCom workshop/, 2011. [[[file:assets/NetSciCom2011.pdf][pdf]]] ~社交网络~

- *[WebSci'10]* Zhaohui Wu, Lu Jiang, Zhenhua Tian, Jun Liu, Qinghua Zheng, and _Junzhou Zhao_. "A Peep at Pornography
  Web in China". In /Proceedings of the Web Science Conference (WebSci)/, 2010. [[[file:assets/WebSci2010.pdf][pdf]]][[[http://www.danwei.com/peoples-pornography-an-interview-with-katrien-jacobs][Media]]] ~Web~
