# -*- fill-column: 120; -*-
#+TITLE: Publications
#+URI: /publication/
#+OPTIONS: toc:nil num:nil


[[[https://scholar.google.com/citations?hl=en&user=hBLT754AAAAJ&view_op=list_works&sortby=pubdate][Google Scholar​]]][[[http://dblp.uni-trier.de/pers/hd/z/Zhao:Junzhou][DBLP​]]][[[file:assets/MLDMAImap.pdf][机器学习、数据挖掘、人工智能领域主流国际会议]]][[[file:assets/CCF2019.pdf][CCF推荐国际会议与期刊目录]]]


- @@html:<span style="color:blue;">@@[SIGKDD'21]@@html:</span>@@ Runze Lei, Pinghui Wang, Rundong Li, Peng Jia,
  _Junzhou Zhao_, Xiaohong Guan, and Chao Deng. "Fast Rotation Kernel Density Estimation over Data Streams". Accepted
  for SIGKDD 2021. [@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[SIGKDD'21]@@html:</span>@@ _Junzhou Zhao_, Pinghui Wang, Chao Deng, and Jing Tao.
  "Temporal Biased Streaming Submodular Optimization". Accepted for SIGKDD 2021. [@@html:<span
  style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[TMC'21]@@html:</span>@@ Feiyang Sun, Pinghui Wang, _Junzhou Zhao_, Nuo Xu, Juxiang
  Zeng, Jing Tao, Kaikai Song, Chao Deng, John C.S. Lui, and Xiaohong Guan. "Mobile Data Traffic Prediction by
  Exploiting Time-Evolving User Mobility Patterns". IEEE Transactions on Mobile Computing. [@@html:<span
  style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[TKDE'21]@@html:</span>@@ Rundong Li, Pinghui Wang, Peng Jia, Xiangliang Zhang,
  _Junzhou Zhao_, Jing Tao, Ye Yuan, and Xiaohong Guan. "Approximately Counting Butterflies in Large Bipartite Graph
  Streams". /IEEE Transactions on Knowledge and Data Engineering (TKDE)/, 2021. [@@html:<span
  style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[SIGMOD'21]@@html:</span>@@ Peng Jia, Pinghui Wang, _Junzhou Zhao_, Shuo Zhang,
  Yiyan Qi, Min Hu, Chao Deng, and Xiaohong Guan. "Bidirectionally Densifying LSH Sketches with Empty Bins".
  /SIGMOD/ 2021. [@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[SIGMOD'21]@@html:</span>@@ Rundong Li, Pinghui Wang, Jiongli Zhu, _Junzhou Zhao_,
  Jia Di, Xiaofei Yang and Kai Ye. "Building Fast and Compact Sketches for Approximately Multi-Set Multi-Membership
  Querying". /SIGMOD/ 2021. [@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[TKDE'21]@@html:</span>@@ Peng Jia, Pinghui Wang, _Junzhou Zhao_, Jing Tao, Ye Yuan,
  Xiaohong Guan. "Erasable Virtual HyperLogLog for Approximating Cumulative Distribution over Data Streams". /IEEE
  Transactions on Knowledge and Data Engineering (TKDE)/, 2021. [@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[AAAI'21]@@html:</span>@@ Shuo Zhang, _Junzhou Zhao_, Pinghui Wang, Nuo Xu, Yang
  Yang, Yiting Liu, Yi Huang, and Junlan Feng. "Learning to Check Contract Inconsistencies". In /Proceedings of the 35th
  AAAI Conference on Artificial Intelligence (AAAI)/, 2021. [[[https://arxiv.org/abs/2012.08150][arXiv]]] [@@html:<span
  style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[KAIS'21]@@html:</span>@@ _Junzhou Zhao_, Pinghui Wang, Zhouguo Chen, Jianwei Ding,
  John C.S. Lui, Don Towsley, and Xiaohong Guan. "Tracking Triadic Cardinality Distributions for Burst Detection in
  High-Speed Graph Streams". /Knowledge and Information Systems (KAIS)/, 2021. [[[https://arxiv.org/abs/1708.09089][arXiv]]]

- @@html:<span style="color:blue;">@@[ACL'20]@@html:</span>@@ Nuo Xu, Pinghui Wang, Long Chen, Li Pan, Xiaoyan Wang and
  _Junzhou Zhao_. "Distinguish Confusing Law Articles for Legal Judgment Prediction". In /Proceedings of the 58th Annual
  Meeting of the Association for Computational Linguistics (ACL)/, 2020. [[[https://arxiv.org/abs/2004.02557][arXiv]]][@@html:<span
  style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[WWW'20]@@html:</span>@@ Yiyan Qi, Pinghui Wang, Yuanming Zhang, _Junzhou Zhao_,
  Guangjian Tian, and Xiaohong Guan. "Fast Generating A Large Number of Gumbel-Max Variables". /The Web Conference
  (WWW)/, 2020. [[[https://arxiv.org/abs/2002.00413][arXiv]]][@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[ICDE'20]@@html:</span>@@ _Junzhou Zhao_, Pinghui Wang, Jing Tao, Shuo Zhang, and
  John C.S. Lui. "Continuously Tracking Core Items in Data Streams with Probabilistic Decays". In /Proceedings of the
  36th IEEE International Conference on Data Engineering (ICDE)/, 2020. [[[file:assets/ICDE2020_full_version.pdf][full paper]]][[[file:assets/ICDE2020_slides.pdf][slides]]][[[file:assets/ICDE2020_poster.pdf][poster]]][@@html:<span
  style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[INS'20]@@html:</span>@@ Lin Lan, Pinghui Wang, _Junzhou Zhao_, Jing Tao, John C.S.
  Lui, and Xiaohong Guan. "Improving Network Embedding with Partially Available Vertex and Edge Content". /Information
  Sciences/, 2020.

- @@html:<span style="color:blue;">@@[TOIS'20]@@html:</span>@@ Xiaoying Zhang, Hong Xie, _Junzhou Zhao_, and John C.S.
  Lui. "Understanding Assimilation-Contrast Effects in Online Rating Systems: Modeling, Debiasing and Applications".
  /ACM Transactions on Information Systems (TOIS)/, 2020. [@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[IJCAI'19]@@html:</span>@@ Nuo Xu, Pinghui Wang, Long Chen, Jing Tao, and Junzhou
  Zhao. "MR-GNN: Multi-Resolution and Dual Graph Neural Network for Predicting Structured Entity Interaction". In
  /Proceedings of the 28th International Joint Conference on Artificial Intelligence (IJCAI)/, 2019.
  [[[https://arxiv.org/abs/1905.09558][arXiv]]][@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[AAAI'19]@@html:</span>@@ _Junzhou Zhao_, S. Shang, Pinghui Wang, John C.S. Lui, and
  Xiangliang Zhang. "Submodular Optimization over Streams with Inhomogeneous Decays". In /Proceedings of the 33rd AAAI
  Conference on Artificial Intelligence (AAAI)/, 2019. [[[https://arxiv.org/abs/1811.05652][arXiv]]][@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[ICDE'19]@@html:</span>@@ _Junzhou Zhao_, S. Shang, Pinghui Wang, John C.S. Lui, and
  Xiangliang Zhang. "Tracking Influential Nodes in Time-Decaying Dynamic Interaction Networks". In /Proceedings of the
  35th IEEE International Conference on Data Engineering (ICDE)/, 2019. [[[https://arxiv.org/abs/1810.07917][arXiv]]][[[file:assets/ICDE19_poster.pdf][poster]]][@@html:<span
  style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[INS'19]@@html:</span>@@ _Junzhou Zhao_, Pinghui Wang, and John C.S. Lui. "Optimizing
  Node Discovery on Networks: Problem Definitions, Fast Algorithms, and Observations". /Information Sciences
  (INS)/, 2019. [[[https://arxiv.org/abs/1703.04307][arXiv]]]

- @@html:<span style="color:blue;">@@[DMKD'19]@@html:</span>@@ _Junzhou Zhao_, Pinghui Wang, John C.S. Lui, Don Towsley,
  and Xiaohong Guan. "Sampling Online Social Networks by Random Walk with Indirect Jumps". /Data Mining and Knowledge
  Discovery (DMKD)/, 2019. [[[https://arxiv.org/abs/1708.09081][arXiv]]]

- @@html:<span style="color:blue;">@@[TKDE'18]@@html:</span>@@ Pinghui Wang, _Junzhou Zhao_, Xiangliang Zhang, Zhenhua Li,
  Jiefeng Cheng, John C.S. Lui, Don Towsley, Jing Tao, and Xiaohong Guan. "MOSS-5: A Fast Method of Approximating Counts
  of 5-Node Graphlets in Large Graphs". /IEEE Transactions on Knowledge and Data Engineering (TKDE)/, 2018.
  [[[file:assets/TKDE18_poster.pdf][poster]]][@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[KAIS'18]@@html:</span>@@ Pinghui Wang, _Junzhou Zhao_, Xiangliang Zhang, Jing Tao,
  and Xiaohong Guan. "SNOD: A Fast Sampling Method of Exploring Node Orbit Degrees for Large Graphs". /Knowledge and
  Information Systems (KAIS)/, 2018.

- @@html:<span style="color:blue;">@@[KAIS'18]@@html:</span>@@ Pinghui Wang, _Junzhou Zhao_, John C.S. Lui, Don Towsley,
  and Xiaohong Guan. "Fast Crawling Methods of Exploring Content Distributed Over Large Graphs". /Knowledge and
  Information Systems (KAIS)/, 2018.

- @@html:<span style="color:blue;">@@[KAIS'18]@@html:</span>@@ Pinghui Wang, _Junzhou Zhao_, Bruno Ribeiro, John C.S. Lui,
  Don Towsley, and Xiaohong Guan. "Practical Characterization of Large Networks Using Neighborhood Information".
  /Knowledge and Information Systems (KAIS)/, 2018.

- @@html:<span style="color:blue;">@@[TKDE'17]@@html:</span>@@ Pinghui Wang, Yiyan Qi, John C.S. Lui, Don Towsley,
  _Junzhou Zhao_, Jing Tao. "Inferring Higher-Order Structure Statistics of Large Networks From Sampled Edges". /IEEE
  Transactions on Knowledge and Data Engineering (TKDE)/, 2017. [@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[INS'17]@@html:</span>@@ _Junzhou Zhao_, John C.S. Lui, Don Towsley, Pinghui Wang,
  and Xiaohong Guan. "I/O-Efficient Calculation of Group Closeness Centrality over Disk-Resident Graphs". /Information
  Sciences (INS)/, 2017.

- @@html:<span style="color:blue;">@@[RecSys'17]@@html:</span>@@ Xiaoying Zhang, _Junzhou Zhao_, and John C.S. Lui.
  "Modeling the Assimilation-Contrast Effects in Online Product Rating Systems: Debiasing and Recommendations". In
  /Proceedings of the 11th ACM Conference on Recommendation Systems (RecSys)/, 2017. [@@html:<span color =
  "red">@@Awarded Best Paper@@html:</span>@@]

- @@html:<span style="color:blue;">@@[ICDE'16]@@html:</span>@@ Pinghui Wang, John C.S. Lui, Don Towsley, and Junzhou
  Zhao. "Minfer: A Method of Inferring Motif Statistics from Sampled Edges". In /Proceedings of the 32nd IEEE
  International Conference on Data Engineering (ICDE)/, 2016. [@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[Thesis]@@html:</span>@@ _Junzhou Zhao_. "Measuring and Monitoring Large-Scale Online
  Social Networks". /Ph.D. thesis, Xi'an Jiaotong University/, 2015.

- @@html:<span style="color:blue;">@@[COSN'15]@@html:</span>@@ _Junzhou Zhao_, John C.S. Lui, Don Towsley, Pinghui Wang,
  and Xiaohong Guan. "Tracking Triadic Cardinality Distributions for Burst Detection in Social Activity Streams". In
  /Proceedings of ACM Conference on Online Social Networks (COSN)/, 2015. [[[http://arxiv.org/abs/1411.3808][arXiv]]]

- @@html:<span style="color:blue;">@@[ICDE'15]@@html:</span>@@ _Junzhou Zhao_, John C.S. Lui, Don Towsley, Pinghui Wang,
  and Xiaohong Guan. "A Tale of Three Graphs: Sampling Design on Hybrid Social-Affiliation Networks". In /Proceedings of
  the 31st IEEE International Conference on Data Engineering (ICDE)/, 2015. [[[file:assets/ICDE2015.pdf][pdf]]][@@html:<span
  style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[TIFS'14]@@html:</span>@@ Pinghui Wang, Xiaohong Guang, _Junzhou Zhao_, Jing Tao, and
  Tao Qin. "A New Sketch Method for Measuring Host Connection Degree Distribution". /IEEE Transactions on Information
  Forensics and Security (TIFS)/, 2014. [@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[SIMPLEX'14]@@html:</span>@@ _Junzhou Zhao_, John C.S. Lui, Don Towsley, and Xiaohong
  Guan. "Measuring and Maximizing Group Closeness Centrality over Disk-Resident Graphs". In /WWW SIMPLEX
  workshop/, 2014. [@@html:<span style="color:red">@@Awarded Best Paper@@html:</span>@@][[[file:assets/SIMPLEX2014.pdf][pdf]]][[[file:assets/NodeGroup_TR.pdf][TR]]]

- @@html:<span style="color:blue;">@@[COMNET'14]@@html:</span>@@ _Junzhou Zhao_, John C.S. Lui, Don Towsley, and Xiaohong
  Guan. "WTF: Efficient Followee Selection for Cascading Outbreak Detection on Online Social Networks". /Computer
  Networks, Special Issue on Online Social Networks/, 2014. [[[file:assets/COMNET2014.pdf][pdf]]]

- @@html:<span style="color:blue;">@@[TKDD'14]@@html:</span>@@ Pinghui Wang, _Junzhou Zhao_, John C.S. Lui, Don Towsley,
  and Xiaohong Guan. "Unbiased Characterization of Node Pairs over Large Graphs". /ACM Transactions on Knowledge
  Discovery from Data (TKDD)/, 2014. [[[file:assets/TKDD2014_node_pair.pdf][pdf]]]

- @@html:<span style="color:blue;">@@[Magazine'14]@@html:</span>@@ Pinghui Wang, Wenbo He, and _Junzhou Zhao_. "A Tale of
  Three Social Networks: User Activity Comparations across Facebook, Twitter, and Foursquare". /IEEE Internet
  Computing/, 2014. [[[file:assets/IC2014.pdf][pdf]]][[[http://stcsn.ieee.net/featured-articles/may2014ataleofthreesocialnetworks][@@html:<span style="color:red">@@Featured Article@@html:</span>@@]]]

- @@html:<span style="color:blue;">@@[TKDD'14]@@html:</span>@@ Pinghui Wang, John C.S. Lui, Bruno Ribeiro, Don Towsley,
  _Junzhou Zhao_, and Xiaohong Guan. "Efficiently Estimating Motif Statistics of Large Networks". /ACM Transactions on
  Knowledge Discovery from Data (TKDD)/, 2014. [[[http://arxiv.org/abs/1306.5288][arXiv]]]

- @@html:<span style="color:blue;">@@[CrowdRec'13]@@html:</span>@@ _Junzhou Zhao_, Xiaohong Guan, and Jing Tao. "On
  Analyzing Estimation Errors due to Constrained Connections in Online Review Systems". /RecSys CrowdRec
  workshop/, 2013. [[[http://arxiv.org/abs/1307.3687][arXiv]]]

- @@html:<span style="color:blue;">@@[ICDE'13]@@html:</span>@@ Pinghui Wang, _Junzhou Zhao_, John C.S. Lui, Don Towsley,
  and Xiaohong Guan. "Sampling Node Pairs Over Large Graphs". In /Proceedings of the 29th IEEE International Conference
  on Data Engineering (ICDE)/, 2013. [[[file:assets/ICDE2013.pdf][pdf]]][@@html:<span style="color:red">@@CCF-A@@html:</span>@@]

- @@html:<span style="color:blue;">@@[NetSciCom'11]@@html:</span>@@ _Junzhou Zhao_, John C.S. Lui, Don Towsley, and
  Xiaohong Guan. "Empirical Analysis of the Evolution of Follower Network: A Case Study on Douban". /IEEE INFOCOM
  NetSciCom workshop/, 2011. [[[file:assets/NetSciCom2011.pdf][pdf]]]

- @@html:<span style="color:blue;">@@[WebSci'10]@@html:</span>@@ Zhaohui Wu, Lu Jiang, Zhenhua Tian, Jun Liu, Qinghua
  Zheng, and _Junzhou Zhao_. "A Peep at Pornography Web in China". In /Proceedings of the Web Science Conference
  (WebSci)/, 2010. [[[file:assets/WebSci2010.pdf][pdf]]][[[http://www.danwei.com/peoples-pornography-an-interview-with-katrien-jacobs][Media]]]
