# -*- fill-column: 120; -*-
#+TITLE: Publication
#+URI: /publication/
#+OPTIONS: toc:nil num:nil

* Publications

[[[https://scholar.google.com/citations?user=hBLT754AAAAJ][Full List]]]

- *[ACL'24]* Shuo Zhang, Liangming Pan, Junzhou Zhao*, and William Yang Wang. "The Knowledge Alignment Problem:
  Bridging Human and External Knowledge for Large Language Models". /Findings of ACL/, 2024. [[[https://arxiv.org/abs/2305.13669][arXiv]]][[[file:assets/MixAlign.pdf][slides]]]

- *[ICDE'24]* Tao Duan, Junzhou Zhao*, Shuo Zhang, Jing Tao, and Pinghui Wang. "Representation Learning of Tangled
  Key-Value Sequence Data for Early Classification". In /Proceedings of the 41st IEEE International Conference on Data
  Engineering (ICDE)/, 2024. [[[https://arxiv.org/abs/2404.07454][arXiv]]][[[file:assets/ICDE2024_slides.pdf][slides]]][[[file:assets/ICDE2024_poster.pdf][poster]]]

- *[TON'24]* Junzhou Zhao, Pinghui Wang, Wei Zhang, Zhaosong Zhang, Maoli Liu, Jing Tao, and John C.S. Lui. "Tracking
  Influencers in Decaying Social Activity Streams with Theoretical Guarantees". /IEEE/ACM Transactions on Networking
  (TON)/, 32(2):1461-1476, 2024.

- *[AAAI'23]* Shuo Zhang, Junzhou Zhao*, Pinghui Wang, Tianxiang Wang, Zi Liang, Jing Tao, Yi Huang, and Junlan Feng.
  "Multi-Action Dialog Policy Learning from Logged User Feedback". In /Proceedings of the 37th AAAI Conference on
  Artificial Intelligence (AAAI)/, 2023. [[[https://arxiv.org/abs/2302.13505][arXiv]]]

- *[SIGMOD'23]* Pinghui Wang, Chengjin Yang, Dongdong Xie, Junzhou Zhao, Hui Li, Jing Tao, and Xiaohong Guan. "An
  Effective and Differentially Private Protocol for Secure Distributed Cardinality Estimation". In /Proceedings of the
  ACM SIGMOD/PODS International Conference on Data Management (SIGMOD)/, 2023. [[[file:assets/SIGMOD23_MPC_slides.pdf][slides]]]

- *[IJCAI'22]* Shuo Zhang, Junzhou Zhao*, Pinghui Wang, Yu Li, Yi Huang, and Junlan Feng. "Think Before You Speak:
  Improving Multi-action Dialog Policy by Planning Single-Action Dialogs". In /Proceedings of the 31st International
  Joint Conference on Artificial Intelligence (IJCAI)/, 2022. [[[https://arxiv.org/abs/2204.11481][arXiv]]][[[file:assets/IJCAI22_MADP_slides.pdf][slides]]]

- *[KDD'21]* Junzhou Zhao, Pinghui Wang, Chao Deng, and Jing Tao. "Temporal Biased Streaming Submodular Optimization".
  In /Proceedings of the 27th ACM SIGKDD Conference on Knowledge Discovery and Data Mining (ACM SIGKDD)/, 2021. [[[file:assets/KDD21_SSO_slides.pdf][slides]]]

- *[AAAI'21]* Shuo Zhang, Junzhou Zhao*, Pinghui Wang, Nuo Xu, Yang Yang, Yiting Liu, Yi Huang, and Junlan Feng.
  "Learning to Check Contract Inconsistencies". In /Proceedings of the 35th AAAI Conference on Artificial Intelligence
  (AAAI)/, 2021. [[[https://arxiv.org/abs/2012.08150][arXiv]]][[[file:assets/AAAI2021-contract_poster.pdf][poster]]]

- *[KAIS'21]* Junzhou Zhao, Pinghui Wang, Zhouguo Chen, Jianwei Ding, John C.S. Lui, Don Towsley, and Xiaohong Guan.
  "Tracking Triadic Cardinality Distributions for Burst Detection in High-Speed Graph Streams". /Knowledge and
  Information Systems (KAIS)/, 63:939-969, 2021. [[[https://arxiv.org/abs/1708.09089][arXiv]]]

- *[ICDE'20]* Junzhou Zhao, Pinghui Wang, Jing Tao, Shuo Zhang, and John C.S. Lui. "Continuously Tracking Core Items
  in Data Streams with Probabilistic Decays". In /Proceedings of the 36th IEEE International Conference on Data
  Engineering (IEEE ICDE)/, 2020. [[[file:assets/ICDE2020_full_version.pdf][full paper]]][[[file:assets/ICDE2020_slides.pdf][slides]]][[[file:assets/ICDE2020_poster.pdf][poster]]]

- *[INS'20]* Lin Lan, Pinghui Wang, Junzhou Zhao, Jing Tao, John C.S. Lui, and Xiaohong Guan. "Improving Network
  Embedding with Partially Available Vertex and Edge Content". /Information Sciences/, 2020.

- *[TOIS'20]* Xiaoying Zhang, Hong Xie, Junzhou Zhao, and John C.S. Lui. "Understanding Assimilation-Contrast Effects
  in Online Rating Systems: Modeling, Debiasing and Applications". /ACM Transactions on Information Systems
  (TOIS)/, 2020.

- *[AAAI'19]* Junzhou Zhao, S. Shang, Pinghui Wang, John C.S. Lui, and Xiangliang Zhang. "Submodular Optimization over
  Streams with Inhomogeneous Decays". In /Proceedings of the 33rd AAAI Conference on Artificial Intelligence
  (AAAI)/, 2019. [[[https://arxiv.org/abs/1811.05652][arXiv]]]

- *[ICDE'19]* Junzhou Zhao, S. Shang, Pinghui Wang, John C.S. Lui, and Xiangliang Zhang. "Tracking Influential Nodes
  in Time-Decaying Dynamic Interaction Networks". In /Proceedings of the 35th IEEE International Conference on Data
  Engineering (IEEE ICDE)/, 2019. [[[https://arxiv.org/abs/1810.07917][arXiv]]][[[file:assets/ICDE19_poster.pdf][poster]]]

- *[INS'19]* Junzhou Zhao, Pinghui Wang, and John C.S. Lui. "Optimizing Node Discovery on Networks: Problem
  Definitions, Fast Algorithms, and Observations". /Information Sciences (INS)/, 477:161-185, 2019. [[[https://arxiv.org/abs/1703.04307][arXiv]]]

- *[DMKD'19]* Junzhou Zhao, Pinghui Wang, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Sampling Online Social
  Networks by Random Walk with Indirect Jumps". /Data Mining and Knowledge Discovery (DMKD)/, 33:24-57, 2019.

- *[TKDE'18]* Pinghui Wang, Junzhou Zhao, Xiangliang Zhang, Zhenhua Li, Jiefeng Cheng, John C.S. Lui, Don Towsley,
  Jing Tao, and Xiaohong Guan. "MOSS-5: A Fast Method of Approximating Counts of 5-Node Graphlets in Large Graphs".
  /IEEE Transactions on Knowledge and Data Engineering (TKDE)/, 2018. [[[file:assets/TKDE18_poster.pdf][poster]]]

- *[KAIS'18]* Pinghui Wang, Junzhou Zhao, Xiangliang Zhang, Jing Tao, and Xiaohong Guan. "SNOD: A Fast Sampling
  Method of Exploring Node Orbit Degrees for Large Graphs". /Knowledge and Information Systems (KAIS)/, 2018.

- *[KAIS'18]* Pinghui Wang, Junzhou Zhao, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Fast Crawling Methods of
  Exploring Content Distributed Over Large Graphs". /Knowledge and Information Systems (KAIS)/, 2018.

- *[KAIS'18]* Pinghui Wang, Junzhou Zhao, Bruno Ribeiro, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Practical
  Characterization of Large Networks Using Neighborhood Information". /Knowledge and Information Systems (KAIS)/, 2018.

- *[INS'17]* Junzhou Zhao, John C.S. Lui, Don Towsley, Pinghui Wang, and Xiaohong Guan. "I/O-Efficient Calculation of
  Group Closeness Centrality over Disk-Resident Graphs". /Information Sciences (INS)/, 2017.

- *[RecSys'17]* Xiaoying Zhang, Junzhou Zhao, and John C.S. Lui. "Modeling the Assimilation-Contrast Effects in Online
  Product Rating Systems: Debiasing and Recommendations". In /Proceedings of the 11th ACM Conference on Recommendation
  Systems (RecSys)/, 2017. ~Awarded Best Paper~

- *[COSN'15]* Junzhou Zhao, John C.S. Lui, Don Towsley, Pinghui Wang, and Xiaohong Guan. "Tracking Triadic Cardinality
  Distributions for Burst Detection in Social Activity Streams". In /Proceedings of ACM Conference on Online Social
  Networks (COSN)/, 2015. [[[http://arxiv.org/abs/1411.3808][arXiv]]]

- *[ICDE'15]* Junzhou Zhao, John C.S. Lui, Don Towsley, Pinghui Wang, and Xiaohong Guan. "A Tale of Three Graphs:
  Sampling Design on Hybrid Social-Affiliation Networks". In /Proceedings of the 31st IEEE International Conference on
  Data Engineering (ICDE)/, 2015. [[[file:assets/ICDE2015.pdf][pdf]]]

- *[SIMPLEX'14]* Junzhou Zhao, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Measuring and Maximizing Group
  Closeness Centrality over Disk-Resident Graphs". In /WWW SIMPLEX workshop/, 2014. [[[file:assets/SIMPLEX2014.pdf][pdf]]][[[file:assets/NodeGroup_TR.pdf][TR]]]
  ~Awarded Best Paper~

- *[COMNET'14]* Junzhou Zhao, John C.S. Lui, Don Towsley, and Xiaohong Guan. "WTF: Efficient Followee Selection for
  Cascading Outbreak Detection on Online Social Networks". /Computer Networks, Special Issue on Online Social
  Networks/, 2014. [[[file:assets/COMNET2014.pdf][pdf]]]

- *[TKDD'14]* Pinghui Wang, Junzhou Zhao, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Unbiased Characterization of
  Node Pairs over Large Graphs". /ACM Transactions on Knowledge Discovery from Data (TKDD)/, 2014. [[[file:assets/TKDD2014_node_pair.pdf][pdf]]]

- *[CrowdRec'13]* Junzhou Zhao, Xiaohong Guan, and Jing Tao. "On Analyzing Estimation Errors due to Constrained
  Connections in Online Review Systems". /RecSys CrowdRec workshop/, 2013. [[[http://arxiv.org/abs/1307.3687][arXiv]]]

- *[ICDE'13]* Pinghui Wang, Junzhou Zhao, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Sampling Node Pairs Over
  Large Graphs". In /Proceedings of the 29th IEEE International Conference on Data Engineering (ICDE)/, 2013. [[[file:assets/ICDE2013.pdf][pdf]]]

- *[NetSciCom'11]* Junzhou Zhao, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Empirical Analysis of the Evolution
  of Follower Network: A Case Study on Douban". /IEEE INFOCOM NetSciCom workshop/, 2011. [[[file:assets/NetSciCom2011.pdf][pdf]]]
