# -*- fill-column: 120; -*-
#+TITLE: Publications
#+URI: /publication/
#+OPTIONS: toc:nil num:nil


* Publications

  [[[https://scholar.google.com/citations?hl=en&user=hBLT754AAAAJ&view_op=list_works&sortby=pubdate][Google Scholar​]]][[[http://dblp.uni-trier.de/pers/hd/z/Zhao:Junzhou][DBLP​]]][[[file:assets/MLDMAImap.pdf][机器学习、数据挖掘、人工智能领域主流国际会议]]][[[file:assets/CCF2019.pdf][CCF推荐国际会议与期刊目录]]]

  # #+INCLUDE: "~/git_project/junzhouzhao.github.io/papers.org"

- Nuo Xu, Pinghui Wang, Long Chen, Li Pan, Xiaoyan Wang and *Junzhou Zhao*. "Distinguish Confusing Law Articles for
  Legal Judgment Prediction". In Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics
  (ACL), 2020. [@@html:<font color="red">@@CCF-A@@html:</font>@@]

- Yiyan Qi, Pinghui Wang, Yuanming Zhang, *Junzhou Zhao*, Guangjian Tian, and Xiaohong Guan. "Fast Generating A Large
  Number of Gumbel-Max Variables". The Web Conference (WWW), 2020. [@@html:<font color="red">@@CCF-A@@html:</font>@@]
  [[[https://arxiv.org/abs/2002.00413][arXiv]]]

- *Junzhou Zhao*, Pinghui Wang, Jing Tao, Shuo Zhang, and John C.S. Lui. "Continuously Tracking Core Items in Data
  Streams with Probabilistic Decays". IEEE International Conference on Data Engineering (ICDE), 2020. [@@html:<font
  color="red">@@CCF-A@@html:</font>@@][[[file:assets/ICDE2020_full_version.pdf][full paper]]][[[file:assets/ICDE2020_slides.pdf][slides]]][[[file:assets/ICDE2020_poster.pdf][poster]]]

- L. Lan, Pinghui Wang, *Junzhou Zhao*, Jing Tao, John C.S. Lui, and Xiaohong Guan. "Improving Network Embedding with
  Partially Available Vertex and Edge Content". Information Sciences, 2020.

- Xiaoying Zhang, Hong Xie, *Junzhou Zhao*, and John C.S. Lui. "Understanding Assimilation-Contrast Effects in Online
  Rating Systems: Modeling, Debiasing and Applications". ACM Transactions on Information Systems (TOIS), 2020.
  [@@html:<font color="red">@@CCF-A@@html:</font>@@]

- Nuo Xu, Pinghui Wang, Long Chen, Jing Tao, and *Junzhou Zhao*. "MR-GNN: Multi-resolution and dual graph neural network
  for predicting structured entity interaction". In Proceedings of the 28th International Joint Conference on Artificial
  Intelligence (IJCAI), 2019. [@@html:<font color="red">@@CCF-A@@html:</font>@@][[[https://arxiv.org/abs/1905.09558][arXiv]]]

- *Junzhou Zhao*, Shuo Shang, Pinghui Wang, John C.S. Lui, and Xiangliang Zhang. "Submodular Optimization over Streams
  with Inhomogeneous Decays". In Proceedings of the 33rd AAAI Conference on Artificial Intelligence (AAAI), 2019.
  [@@html:<font color="red">@@CCF-A@@html:</font>@@][[[https://arxiv.org/abs/1811.05652][arXiv]]]

- *Junzhou Zhao*, Shuo Shang, Pinghui Wang, John C.S. Lui, and Xiangliang Zhang. "Tracking Influential Nodes in
  Time-Decaying Dynamic Interaction Networks". In Proceedings of the 35th IEEE International Conference on Data
  Engineering (ICDE), 2019. [@@html:<font color="red">@@CCF-A@@html:</font>@@][[[https://arxiv.org/abs/1810.07917][arXiv]]][[[file:assets/ICDE19_poster.pdf][poster]]]

- *Junzhou Zhao*, Pinghui Wang, and John C.S. Lui. "Optimizing Node Discovery on Networks: Problem Definitions, Fast
  Algorithms, and Observations". Information Sciences (INS), 2019. [[[https://arxiv.org/abs/1703.04307][arXiv]]]

- *Junzhou Zhao*, Pinghui Wang, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Sampling Online Social Networks by
  Random Walk with Indirect Jumps". Data Mining and Knowledge Discovery (DMKD), 2019. [[[https://arxiv.org/abs/1708.09081][arXiv]]]

- Pinghui Wang, *Junzhou Zhao*, Xiangliang Zhang, Zhenhua Li, Jiefeng Cheng, John C.S. Lui, Don Towsley, Jing Tao, and
  Xiaohong Guan. "MOSS-5: A Fast Method of Approximating Counts of 5-Node Graphlets in Large Graphs". IEEE Transactions
  on Knowledge and Data Engineering (TKDE), 2018. [@@html:<font color="red">@@CCF-A@@html:</font>@@][[[file:assets/TKDE18_poster.pdf][poster]]]

- Pinghui Wang, *Junzhou Zhao*, Xiangliang Zhang, Jing Tao, and Xiaohong Guan. "SNOD: A Fast Sampling Method of
  Exploring Node Orbit Degrees for Large Graphs". Knowledge and Information Systems (KAIS), 2018.

- Pinghui Wang, *Junzhou Zhao*, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Fast Crawling Methods of Exploring
  Content Distributed Over Large Graphs". Knowledge and Information Systems (KAIS), 2018.

- Pinghui Wang, *Junzhou Zhao*, Bruno Ribeiro, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Practical
  Characterization of Large Networks Using Neighborhood Information". Knowledge and Information Systems (KAIS), 2018.

- Pinghui Wang, Yiyan Qi, John C.S. Lui, Don Towsley, *Junzhou Zhao*, Jing Tao. "Inferring Higher-Order Structure
  Statistics of Large Networks From Sampled Edges". IEEE Transactions on Knowledge and Data Engineering (TKDE), 2017.
  [@@html:<font color="red">@@CCF-A@@html:</font>@@]

- *Junzhou Zhao*, John C.S. Lui, Don Towsley, Pinghui Wang, and Xiaohong Guan. "I/O-Efficient Calculation of Group
  Closeness Centrality over Disk-Resident Graphs". Information Sciences (INS), 2017.

- Xiaoying Zhang, *Junzhou Zhao*, and John C.S. Lui. "Modeling the Assimilation-Contrast Effects in Online Product
  Rating Systems: Debiasing and Recommendations". In Proceedings of the 11th ACM Conference on Recommendation Systems
  (RecSys), 2017. [@@html:<font color = "red">@@Awarded Best Paper@@html:</font>@@]

- Pinghui Wang, John C.S. Lui, Don Towsley, and *Junzhou Zhao*. "Minfer: A Method of Inferring Motif Statistics from
  Sampled Edges". In Proceedings of the 32nd IEEE International Conference on Data Engineering (ICDE), 2016.
  [@@html:<font color="red">@@CCF-A@@html:</font>@@]

- *Junzhou Zhao*, John C.S. Lui, Don Towsley, Pinghui Wang, and Xiaohong Guan. "Tracking Triadic Cardinality
  Distributions for Burst Detection in Social Activity Streams". In Proceedings of ACM Conference on
  Online Social Networks (COSN), 2015. [[[http://arxiv.org/abs/1411.3808][arXiv]]]

- *Junzhou Zhao*, John C.S. Lui, Don Towsley, Pinghui Wang, and Xiaohong Guan. "A Tale of Three Graphs: Sampling Design
  on Hybrid Social-Affiliation Networks". In Proceedings of the 31st IEEE International Conference on Data Engineering
  (ICDE), 2015. [@@html:<font color="red">@@CCF-A@@html:</font>@@][[[file:assets/ICDE2015.pdf][pdf]]]

- Pinghui Wang, Xiaohong Guang, *Junzhou Zhao*, Jing Tao, and Tao Qin. "A New Sketch Method for Measuring Host
  Connection Degree Distribution". IEEE Transactions on Information Forensics and Security (TIFS), 2014. [@@html:<font
  color="red">@@CCF-A@@html:</font>@@]

- *Junzhou Zhao*. "Measuring and Monitoring Large-Scale Online Social Networks". Ph.D. thesis, Xi'an Jiaotong
  University, 2015.

- *Junzhou Zhao*, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Measuring and Maximizing Group Closeness Centrality
  over Disk-Resident Graphs". In WWW SIMPLEX workshop, 2014. [@@html:<font color="red">@@Awarded Best
  Paper@@html:</font>@@][[[file:assets/SIMPLEX2014.pdf][pdf]]][[[file:assets/NodeGroup_TR.pdf][TR]]]

- *Junzhou Zhao*, John C.S. Lui, Don Towsley, and Xiaohong Guan. "WTF: Efficient Followee Selection for Cascading
  Outbreak Detection on Online Social Networks". Computer Networks, Special Issue on Online Social Networks, 2014. [[[file:assets/COMNET2014.pdf][pdf]]]

- Pinghui Wang, *Junzhou Zhao*, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Unbiased Characterization of Node Pairs
  over Large Graphs". ACM Transactions on Knowledge Discovery from Data (TKDD), 2014. [[[file:assets/TKDD2014_node_pair.pdf][pdf]]]

- Pinghui Wang, Wenbo He, and *Junzhou Zhao*. "A Tale of Three Social Networks: User Activity Comparations across
  Facebook, Twitter, and Foursquare". IEEE Internet Computing, 2014. [[[file:assets/IC2014.pdf][pdf]]][[[http://stcsn.ieee.net/featured-articles/may2014ataleofthreesocialnetworks][@@html:<font color="red">@@Featured
  Article@@html:</font>@@]]]

- Pinghui Wang, John C.S. Lui, Bruno Ribeiro, Don Towsley, *Junzhou Zhao*, and Xiaohong Guan. "Efficiently Estimating
  Motif Statistics of Large Networks". ACM Transactions on Knowledge Discovery from Data (TKDD), 2014. [[[http://arxiv.org/abs/1306.5288][arXiv]]]

- *Junzhou Zhao*, Xiaohong Guan, and Jing Tao. "On Analyzing Estimation Errors due to Constrained Connections in Online
  Review Systems". RecSys CrowdRec workshop, 2013. [[[http://arxiv.org/abs/1307.3687][arXiv]]]

- Pinghui Wang, *Junzhou Zhao*, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Sampling Node Pairs Over Large Graphs".
  In Proceedings of the 29th IEEE International Conference on Data Engineering (ICDE), 2013. [@@html:<font
  color="red">@@CCF-A@@html:</font>@@][[[file:assets/ICDE2013.pdf][pdf]]]

- *Junzhou Zhao*, John C.S. Lui, Don Towsley, and Xiaohong Guan. "Empirical Analysis of the
  Evolution of Follower Network: A Case Study on Douban". IEEE INFOCOM NetSciCom workshop, 2011.
  [[[file:assets/NetSciCom2011.pdf][pdf]]]

- Zhaohui Wu, Lu Jiang, Zhenhua Tian, Jun Liu, Qinghua Zheng, and *Junzhou Zhao*. "A Peep at
  Pornography Web in China". In Proceedings of the Web Science Conference (WebSci), 2010.
  [[[file:assets/WebSci2010.pdf][pdf]]][[[http://www.danwei.com/peoples-pornography-an-interview-with-katrien-jacobs][Media]]]


** Undated

  # #+INCLUDE: "~/git_project/junzhouzhao.github.io/undated.org"

- *Junzhou Zhao*, Pinghui Wang, John C.S. Lui, and Don Towsley. "Tracking Triadic Cardinality Distributions for
  Burst Detection in Multigraph Streams". [[[https://arxiv.org/abs/1708.09089][arXiv]]]
